# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPreference',
            new_name='UserTags',
        ),
    ]
