# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20160708_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandTags',
            new_name='BrandTag',
        ),
        migrations.RenameModel(
            old_name='OfferTags',
            new_name='OfferTag',
        ),
        migrations.RenameModel(
            old_name='UserTags',
            new_name='UserTag',
        ),
    ]
