---
phraseapp:
  project_id: b5faeed36d2dea17abd051208b72ac78
  pull:
    targets:
    - file: locales/<locale_name>.json
      params:
        file_format: nested_json
  push:
    sources:
    - file: locales/<locale_name>.json
      params:
        file_format: nested_json
