# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20160708_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='pathLogo',
            field=models.FilePathField(path='/tmp/logos/'),
        ),
    ]
